// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRG973jCV4l3sdDIMZQ18ibb3K0cShqzs',
    appId: '1:542127441373:web:1bd46620a0c9141f19e234',
    messagingSenderId: '542127441373',
    projectId: 'firestore-practice-ff608',
    authDomain: 'firestore-practice-ff608.firebaseapp.com',
    storageBucket: 'firestore-practice-ff608.firebasestorage.app',
    measurementId: 'G-GV54X2NYS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAN3OS7UszR5ZkVDnIMVQZow3pm1956HA',
    appId: '1:542127441373:android:84064f4d4abdc22119e234',
    messagingSenderId: '542127441373',
    projectId: 'firestore-practice-ff608',
    storageBucket: 'firestore-practice-ff608.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRG973jCV4l3sdDIMZQ18ibb3K0cShqzs',
    appId: '1:542127441373:web:b90012e682e58ed219e234',
    messagingSenderId: '542127441373',
    projectId: 'firestore-practice-ff608',
    authDomain: 'firestore-practice-ff608.firebaseapp.com',
    storageBucket: 'firestore-practice-ff608.firebasestorage.app',
    measurementId: 'G-L0GXYXQSQS',
  );
}
